import random

war_cards = []
Player1Deck = []
Player2Deck = []
# Player1Deck = ['3','6','4', '4','2', '3','6','4']
# Player2Deck = ['9','2','4', '4','8', '9','K','4']
card_values = ('2', '3', '4', '5', '6', '7', '8', '9', '10', 'J', 'K', 'Q', 'A')
winner = ""
war = False

def PrepareDeck():
    """
    Generates the deck of cards, shuffles it before dealing them to the two players
    """
    deck = [val for val in card_values for i in range(4)]
    random.shuffle(deck)
    for i in range(26):
        Player1Deck.append(deck.pop())
        Player2Deck.append(deck.pop())


def CompareCards():
    global war
    status()
    card1 = Player1Deck.pop(0)
    card2 = Player2Deck.pop(0)
    print("The cards played by each player : ")
    print("Player 1  :  ", card1)
    print("Player 2  :  ", card2)
    game_cards = []
    game_cards.append(card1)
    game_cards.append(card2)
    if card_values.index(card1) == card_values.index(card2):
        print("at war")
        war = True
        war_cards.extend(game_cards)
        for i in range(3):
            war_cards.append(Player1Deck.pop(0))
            war_cards.append(Player2Deck.pop(0))
        print("war cards : ", war_cards)
    else:
        if card_values.index(card1) > card_values.index(card2):
            print("player 1 wins the round!!")
            print("value of war ", war)
            if war:
                Player1Deck.extend(war_cards)
                war_cards.clear()
                war = False
            Player1Deck.extend(game_cards)
        else:
            print("player 2 wins the round!!")
            print("game cards: ", game_cards)
            if war:
                Player2Deck.extend(war_cards)
                war_cards.clear()
                war = False
            Player2Deck.extend(game_cards)


def status():
    print("Player 1 deck :")
    print(Player1Deck)
    print("Player 2 deck :")
    print(Player2Deck)
    print("Player 1 has :", len(Player1Deck), " cards")
    print("Player 2 has :", len(Player2Deck), " cards")

def WarGame():
    """
    :return:
    """
    while len(Player1Deck) > 3 and len(Player2Deck) > 3:
        CompareCards()

if __name__ == '__main__':
    """
    Pile of cards generated by each player during the game. 
    """
    """ The cards dealt to each player"""
    PrepareDeck()
    WarGame()
