"""
THE WAR CARD GAME:
Programming assignment for Intel Interview.
Author : Harini Gowdagere Tulaisdas

Assumptions : 1. Suit doesnt matter

List extend is used to add the card to the bottom of the deck.


"""
import random

player1_pile = []
player2_pile = []
Player1Deck = []
Player2Deck = []
card_values = ('2', '3', '4', '5', '6', '7', '8', '9', '10', 'J', 'K', 'Q', 'A')
winner = ""
war = False

def PrepareDeck():
    """
    Generates the deck of cards, shuffles it before dealing them to the two players
    """
    deck = [val for val in card_values for i in range(4)]
    random.shuffle(deck)
    for i in range(52):
        if i % 2 == 0:
            Player1Deck.append(deck[i])
        else:
            Player2Deck.append(deck[i])


def AtWar():
    """
    pops 4 cards from top of the both the decks and makes a pile of them
    :return:
    """
    if len(Player1Deck) > 4 and len(Player2Deck) > 4:
        for i in range(4):
            player1_pile.append(Player1Deck.pop(0))
            player2_pile.append(Player2Deck.pop(0))
    print("Last card played after war :", " Player 1 : ", player1_pile[3] , " Player 2 : " , player2_pile[3])
    CompareCards(player1_pile[3], player2_pile[3])



def AdjustCardsAfterBattle(card1,card2,deck):
    """

    :param card1:
    :param card2:
    :param deck:
    :return:
    """
    if war == False :
        deck.extend(card1)
        deck.extend(card2)

def CompareCards(P1, P2):
    """

    :param P1:
    :param P2:
    :return:
    """
    global war
    if card_values.index(P1) == card_values.index(P2):
        print("Player 1 and Player 2 are at war!!")
        war = True
        if len(Player1Deck) > 4 and len(Player2Deck) > 4:
            AtWar()
        else:
            winner = "Player 1" if len(Player1Deck) > len(Player2Deck) else "Player 2"

    if card_values.index(P1) > card_values.index(P2):
        print("player 1 wins the round!!")
        if war == False:
            AdjustCardsAfterBattle(P1,P2,Player1Deck);
        else:
            player1_pile.extend(player2_pile)
            Player1Deck.extend(player1_pile)
            player1_pile.clear()
    else:
        print("player 2 wins the round!!")
        if war == False:
            AdjustCardsAfterBattle(P1, P2, Player2Deck);
        else:
            player2_pile.extend(player1_pile)
            Player2Deck.extend(player2_pile)
            player2_pile.clear()


def WarGame():
    """

    :return:
    """
    while len(Player1Deck) > 0 and len(Player2Deck) > 0:
        card1 = Player1Deck.pop()
        card2 = Player2Deck.pop()
        print("The cards played by each player : ")
        print("Player 1  :  ", card1)
        print("Player 2  :  ", card2)
        CompareCards(card1, card2)

if __name__ == '__main__':
    """
    Pile of cards generated by each player during the game. 
    """
    """ The cards dealt to each player"""
    PrepareDeck()
    # print("Player 1 Deck : ", Player1Deck)
    # print("Player 2 Deck : ", Player2Deck)
    WarGame()



